# How many emails were sent for each campaign?
select campaign_id,campaign_name,count(*) as email_sent from email_marketing
group by campaign_id,campaign_name
order by email_sent;

# What is the open rate and click-through rate for each campaign?
select campaign_id,campaign_name,count(*) as email_sent,
sum(email_opened)*1.0/count(*) as email_open_rate,
sum(email_clicked)*1.0/count(*) as email_click_rate
from email_marketing
group by campaign_id,campaign_name
order by email_sent desc;

#Which campaigns lead to the highest number of purchases?
select campaign_id,campaign_name,sum(purchase_made) as total_purchases 
from email_marketing
group by campaign_id,campaign_name
order by total_purchases desc
limit 1;

#Which campaigns have conversion rates higher than the overall average?

select campaign_id,campaign_name ,sum(purchase_made)*1.0/count(*) as conversion_rate
from email_marketing
group by campaign_id,campaign_name
having sum(purchase_made)*1.0/count(*)>(select sum(purchase_made)*1.0/count(*) from email_marketing);

#How do customers behave after opening or clicking emails?
select * from email_marketing;
select count(*) as Total_emails, sum(case
 when email_opened=1 and email_clicked=1 then 1 
 end) as clicked_after_open,
 sum(case when 
 email_clicked=1 and purchase_made=1 then 1
 end)as purchased_after_click
from  email_marketing;

#Which customers consistently open emails but never make a purchase?
select customer_id, sum(email_opened) as times_opened
from email_marketing
group by customer_id
having sum(email_opened)>0
and sum(purchase_made)=0
order by times_opened desc;

#What is the impact of device type (Mobile, Desktop, Tablet) on open and click behaviour?
select device_type,count(*),sum(email_opened) as total_openers,sum(email_clicked) as total_clickers,
sum(email_opened)*1.0/count(*) open_rate_pct,
sum(email_clicked)*1.0/count(*) click_rate_pct
from email_marketing
group by device_type;

#Which cities show the highest customer engagement?
select customer_city,sum(email_opened)*1.0/count(*) as open_rate from email_marketing
group by customer_city
order by open_rate desc
limit 1;

#How much total revenue is generated by each campaign?
select campaign_id,campaign_name,sum(purchase_amount) as total_revenue from email_marketing
group by campaign_id,campaign_name;

select campaign_id,campaign_name,sum(purchase_amount)/SUM(purchase_made) as AOV from email_marketing
group by campaign_id,campaign_name
ORDER BY AOV DESC
LIMIT 1;

select campaign_id,campaign_name,sum(purchase_amount)/SUM(purchase_made) as AOV from email_marketing
group by campaign_id,campaign_name
ORDER BY AOV DESC
LIMIT 1;

#What is the revenue contribution by city and device type?
select customer_city,device_type,sum(purchase_amount) as revenue from email_marketing
group by customer_city,device_type
order by revenue desc;
#•	Which campaigns contribute to the top 80% of total revenue?
with campaign_revenue AS 
(select campaign_id,campaign_name,sum(purchase_amount) as revenue from email_marketing
group by campaign_id,campaign_name
order by revenue desc),
revenue_rank as (select campaign_id,campaign_name,revenue, sum(revenue) over(order by revenue desc) as cumulative_revenue,
sum(revenue)over() as total_revenue
from campaign_revenue)
select campaign_id,campaign_name,round(cumulative_revenue*100.0/total_revenue,2) as cumulative_pct from revenue_rank
where cumulative_revenue<=0.8*total_revenue;
select*from email_marketing;